// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Subtitle string `json:"subtitle"`
	Content  string `json:"content"`
}

type Blog struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Subtitle string `json:"subtitle"`
	Content  string `json:"content"`
	Summary  string `json:"summary"`
	Tags     []*Tag `json:"tags"`
}

type NewArticle struct {
	ID       *string `json:"id"`
	Title    string  `json:"title"`
	Subtitle string  `json:"subtitle"`
	Content  string  `json:"content"`
}

type NewBlog struct {
	ID       *string `json:"id"`
	Title    string  `json:"title"`
	Subtitle string  `json:"subtitle"`
	Content  string  `json:"content"`
	Summary  *string `json:"summary"`
}

type NewPost struct {
	ID      *string   `json:"id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
	Tags    []*string `json:"tags"`
}

type NewTag struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type Post struct {
	ID      string   `json:"id"`
	Title   *string  `json:"title"`
	Content string   `json:"content"`
	Tags    []string `json:"tags"`
}

type Tag struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}
